Platforms:
  #You can make as many Platforms as you want!
  youtube:
    domain: youtube.com
    #If player uses http:// or https:// this will be automatically deleted in the final message.
    message:
      - "&b&m--------------------------"
      - "     &e%player% &fis on &c&lY&f&lT "
      - "&d--> &f%link% &d<--     "
      - "&b&m--------------------------"
  twitch:
    domain: twitch.tv
    message:
      - "&b&m--------------------------"
      - "  &e%player% &fis on &dtwitch "
      - "&d--> &f%link% &d<--     "
      - "&b&m--------------------------"
Config:
  StreamPermission: "StreamX.stream"
  #Permission to execute /stream cmd.
  AdminPermission: "StreamX.*"
  #Permission to execute the admin cmd.
  Cooldown: 30
  #Cooldown in seconds.
Messages:
  Method: "&fYour &e/stream stream <link> &fmust include the respective domain."
  InCooldown: "&f[&c-&f] You are in cooldown. You must wait for %cooldown%"
  Reload: "&f[&a+&f] Reload Successfully!"
  NoPerms: "&f[&c-&f] You don't have permission to do that!"
  NoLink: "&f[&c-&f] You must use &e/strem <link>"
  NoRecognized: "&f[&c-&f] This link is not recognized!"
TwitchApi:
  #This api is used to send a message in chat if any of the streamers in config are streaming in twitch
  Enable: true
  #The streamers that the api will be looking for.
  Streamers:
  - QueensGamingPalace
  - kiritokirigami25
  DelayCheck: 120
  #Delay in seconds
  Message:
    - "&b&m--------------------------"
    - "  &e%player% &fis on &dtwitch "
    - "&d--> &f%link% &d<--     "
    - "&b&m--------------------------"